package validators

import (
	"github.com/michaelolof/gofi/validators/rules"
)

const (
	ReuestType   rules.ValidatorOptionType = 1
	ResponseType rules.ValidatorOptionType = 2
)

var Validators = rules.ContextValidators{
	"required":         rules.IsRequired,
	"oneof":            rules.IsOneOf,
	"max":              rules.IsMax,
	"min":              rules.IsMin,
	"cidr":             rules.IsCIDR,
	"cidrv4":           rules.IsCIDRv4,
	"cidrv6":           rules.IsCIDRv6,
	"datauri":          rules.IsDataURI,
	"fileUrl":          rules.IsFileURL,
	"fqdn":             rules.IsFQDN,
	"hostname":         rules.IsHostnameRFC952,
	"hostname_port":    rules.IsHostnamePort,
	"hostname_rfc1123": rules.IsHostnameRFC1123,
	"ip":               rules.IsIP,
	"ip4_addr":         rules.IsIP4AddrResolvable,
	"ip6_addr":         rules.IsIP6AddrResolvable,
	"ip_addr":          rules.IsIPAddrResolvable,
	"ipv4":             rules.IsIPv4,
	"ipv6":             rules.IsIPv6,
	"mac":              rules.IsMAC,
	"not_empty":        rules.IsNotEmpty,
	"tcp4_addr":        rules.IsTCP4AddrResolvable,
	"tcp6_addr":        rules.IsTCP6AddrResolvable,
	"tcp_addr":         rules.IsTCPAddrResolvable,
	"udp4_addr":        rules.IsUDP4AddrResolvable,
	"udp6_addr":        rules.IsUDP6AddrResolvable,
	"udp_addr":         rules.IsUDPAddrResolvable,
	"unix_addr":        rules.IsUnixAddrResolvable,
	"uri":              rules.IsURI,
	"url":              rules.IsURL,
	"http_url":         rules.IsHttpURL,
	"url_encoded":      rules.IsURLEncoded,
	"urn_rfc2141":      rules.IsUrnRFC2141,

	// Regex Rules
	"alpha":              rules.IsAlpha,
	"alphanum":           rules.IsAlphaNumeric,
	"alphaunicode":       rules.IsAlphaUnicode,
	"alphaunicodenum":    rules.IsAlphaUnicodeNumeric,
	"ascii":              rules.IsASCII,
	"printascii":         rules.IsPrintableASCII,
	"multibyte":          rules.IsMultibyte,
	"numeric":            rules.IsNumeric,
	"number":             rules.IsNumber,
	"hexadecimal":        rules.IsHexadecimal,
	"hexcolor":           rules.IsHexColor,
	"rgb":                rules.IsRGB,
	"rgba":               rules.IsRGBA,
	"hsl":                rules.IsHSL,
	"hsla":               rules.IsHSLA,
	"email":              rules.IsEmail,
	"e164":               rules.IsE164,
	"isbn10":             rules.IsISBN10,
	"isbn13":             rules.IsISBN13,
	"issn":               rules.IsISSN,
	"uuid":               rules.IsUUID,
	"uuid3":              rules.IsUUID3,
	"uuid4":              rules.IsUUID4,
	"uuid5":              rules.IsUUID5,
	"uuid_rfc4122":       rules.IsUUIDRFC4122,
	"uuid3_rfc4122":      rules.IsUUID3RFC4122,
	"uuid4_rfc4122":      rules.IsUUID4RFC4122,
	"uuid5_rfc4122":      rules.IsUUID5RFC4122,
	"ulid":               rules.IsULID,
	"ssn":                rules.IsSSN,
	"bic":                rules.IsBIC,
	"semver":             rules.IsSemver,
	"cve":                rules.IsCVE,
	"base32":             rules.IsBase32,
	"base64":             rules.IsBase64,
	"base64url":          rules.IsBase64URL,
	"base64rawurl":       rules.IsBase64RawURL,
	"md4":                rules.IsMD4,
	"md5":                rules.IsMD5,
	"sha256":             rules.IsSHA256,
	"sha384":             rules.IsSHA384,
	"sha512":             rules.IsSHA512,
	"ripemd128":          rules.IsRIPEMD128,
	"ripemd160":          rules.IsRIPEMD160,
	"tiger128":           rules.IsTiger128,
	"tiger160":           rules.IsTiger160,
	"tiger192":           rules.IsTiger192,
	"html_encoded":       rules.IsHTMLEncoded,
	"html":               rules.IsHTML,
	"jwt":                rules.IsJWT,
	"cron":               rules.IsCron,
	"spicedb_id":         rules.IsSpiceDBID,
	"spicedb_permission": rules.IsSpiceDBPermission,
	"spicedb_type":       rules.IsSpiceDBType,
	"latitude":           rules.IsLatitude,
	"longitude":          rules.IsLongitude,
	"btc_addr":           rules.IsBTCAddress,
	"btc_addr_bech32":    rules.IsBTCAddressBech32,
	"eth_addr":           rules.IsETHAddress,
	"mongodb":            rules.IsMongoDB,

	// String Rules
	"contains":     rules.Contains,
	"containsany":  rules.ContainsAny,
	"containsrune": rules.ContainsRune,
	"excludes":     rules.Excludes,
	"excludesall":  rules.ExcludesAll,
	"excludesrune": rules.ExcludesRune,
	"startswith":   rules.StartsWith,
	"endswith":     rules.EndsWith,
	"lowercase":    rules.IsLowercase,
	"uppercase":    rules.IsUppercase,

	// Comparison Rules
	"len": rules.IsLen,
	"eq":  rules.IsEq,
	"ne":  rules.IsNe,
	"lt":  rules.IsLt,
	"gt":  rules.IsGt,
	"lte": rules.IsLte,
	"gte": rules.IsGte,

	// Time Rules
	"datetime": rules.IsDatetime,
	"timezone": rules.IsTimezone,

	// File Rules
	"file":     rules.IsFile,
	"dir":      rules.IsDir,
	"filepath": rules.IsFilePath,

	// Misc Rules
	"boolean": rules.IsBoolean,
	"json":    rules.IsJSON,
	"default": rules.IsDefault,

	// Payment Rules
	"credit_card":   rules.IsCreditCard,
	"ein":           rules.IsEIN,
	"luhn_checksum": rules.HasLuhnChecksum,
}
